name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - master  # Use master instead of main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build and Export Next.js
        run: |
          npm run build
          npm run export
          touch out/.nojekyll  # Prevent GitHub Pages from ignoring static files

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Deploy to gh-pages branch
          folder: out
